#!/bin/bash

CONFIGPATH=arch/arm/configs/
LINEBREAK=\\r\\n

OLDLINE=$1
NEWLINE=$2

DEVICES=(
         "cm_rhine_amami_row_defconfig"
         "cm_rhine_honami_row_defconfig"
         "cm_shinano_sirius_defconfig"
         "cm_shinano_leo_defconfig"
         "cm_shinano_aries_defconfig"
         "cm_shinano_castor_defconfig"
         "cm_shinano_castor_windy_defconfig"
        )

if( [ ! -z $OLDLINE ] && [ ! -z $NEWLINE ]  );
then

for i in ${DEVICES[@]}
do
sed -i s/${OLDLINE}/${OLDLINE}${LINEBREAK}${NEWLINE}/ ${CONFIGPATH}${i}
done

fi
